# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "file://*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "chrome://*/*")

# Enable JavaScript.
# Type: Bool
config.set("content.javascript.enabled", True, "qute://*/*")


# Bindings
# Focus on next and previous tabs
config.bind("<Ctrl-Tab>", "tab-next")
config.bind("<Ctrl-Shift-Tab>", "tab-prev")

# Page up and page down
config.bind("<Ctrl-D>", "scroll-page 0 -1")
config.bind("<Ctrl-F>", "scroll-page 0 1")

config.unbind("q")

# Set search engines
config.set("url.searchengines", {
    "DEFAULT": "https://www.google.com.au/search?q={}",
    "!g": "https://www.google.com.au/search?q={}",
    "!r": "https://old.reddit.com/r/{}",
    "!rs": "https://old.reddit.com/search?q={}",
    "!yt": "https://www.youtube.com/results?search_query={}",
    "!wiki": "https://en.wikipedia.org/wiki/Search?search={}"
})

# General settings
config.set("content.notifications", False)
config.set("content.pdfjs", True)
config.set("editor.command", ["vim", "{file}"])

# Font settings
config.set("fonts.completion.category", "7pt inconsolata")
config.set("fonts.completion.entry", "7pt inconsolata")
config.set("fonts.downloads", "bold 7pt inconsolata")
config.set("fonts.hints", "bold 7pt inconsolata")
config.set("fonts.keyhint", "bold 7pt inconsolata")
config.set("fonts.messages.error", "7pt inconsolata")
config.set("fonts.messages.info", "7pt inconsolata")
config.set("fonts.messages.warning", "7pt inconsolata")
config.set("fonts.prompts", "7pt inconsolata")
config.set("fonts.statusbar", "bold 7pt inconsolata")
config.set("fonts.tabs.selected", "bold 7pt inconsolata")
config.set("fonts.tabs.unselected", "bold 7pt inconsolata")

config.set("fonts.web.family.fixed", "inconsolata")
config.set("fonts.web.family.sans_serif", "IBM Plex Sans")
config.set("fonts.web.family.serif", "IBM Plex Serif")

# Keyhint settings
config.set("keyhint.radius", 0)

# Scroll settings
config.set("scrolling.bar", "when-searching")
config.set("scrolling.smooth", True)

# Status bar settings
config.set("statusbar.padding", {"bottom": 2, "left": 1, "right": 1, "top": 2})

# Tab settings
config.set("tabs.background", True)
config.set("tabs.last_close", "close")
config.set("tabs.max_width", -1)
config.set("tabs.min_width", 60)
config.set("tabs.position", "top")
config.set("tabs.show", "multiple")
config.set("tabs.title.alignment", "left")
config.set("tabs.padding", {"bottom": 2, "left": 4, "right": 4, "top": 2})

# Url settings
config.set("url.default_page", "https://julian-heng.gitlab.io/startpage")
config.set("url.start_pages", [config.get("url.default_page")])

# Set colors
config.source("base16-tomorrow-night.config.py")
