variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - lint

shellcheck:
  image: ubuntu:latest
  stage: lint
  before_script:
    - apt --yes update && apt --yes install shellcheck
    - shellcheck --version
  script:
    - shopt -s globstar
    - shopt -s extglob
    - |
        shellcheck \
          bashrc/bash* \
          bashrc/modules/* \
          bspwm/* \
          polybar/polybar_bspwm \
          polybar/reload \
          scripts/color/*.bash \
          scripts/info/* \
          scripts/utils/count_lines \
          scripts/utils/feh-wal \
          scripts/utils/iommu \
          scripts/utils/nvidia_toggle \
          scripts/utils/open_iterm2 \
          scripts/utils/ozbargain-cli \
          scripts/utils/vim-plugins \
          scripts/utils/wal \
          scripts/utils/xfce-wal \
          tmux/info.bash \
          yabai/yabairc
  rules:
    - changes:
      - bashrc/bash*
      - bashrc/modules/*
      - bspwm/*
      - polybar/polybar_bspwm
      - polybar/reload
      - scripts/color/*.bash
      - scripts/info/*
      - scripts/utils/android_debloat
      - scripts/utils/count_lines
      - scripts/utils/feh-wal
      - scripts/utils/iommu
      - scripts/utils/nvidia_toggle
      - scripts/utils/open_iterm2
      - scripts/utils/ozbargain-cli
      - scripts/utils/vim-plugins
      - scripts/utils/wal
      - scripts/utils/xfce-wal
      - tmux/info.bash
      - yabai/yabairc

python-lint:
  image: python:slim
  stage: lint
  before_script:
    - python -V
    - type -p python
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install pylint flake8
  script:
    - |
        python -m pylint ./scripts/color/coins.py \
                         ./scripts/utils/update-git-repos
    - |
        python -m flake8 ./scripts/color/coins.py \
                         ./scripts/utils/update-git-repos
  rules:
    - changes:
      - scripts/color/coins.py
      - scripts/utils/update-git-repos
