#!/usr/bin/env bash

git_run()
{
    local dir="$1"
    local old_pwd
    local status
    local -a cmds
    cmds=("${@:2}")

    [[ ! "${git_version[*]}" ]] && {
        _git="$(git --version)"
        _git="${_git/* }"
        IFS=$'\n' read -d '' -ra git_version <<< "${_git//\./$'\n'}"
    }

    if [[ "${old_git}" ]] || ((git_version[0] == 1 && git_version[1] == 8 && git_version[2] < 5)); then
        old_git="true"
        old_pwd="${PWD:-$(pwd)}"

        cd "${dir}" || return 1
        git "${cmds[@]}"
        status="$?"
        cd "${old_pwd}" || return 1
    else
        git -C "${dir}" "${cmds[@]}"
        status="$?"
    fi

    return "${status}"
}

get_repos()
{
    while (($# > 0)); do
        for dir in "${1%/}/"*; do
            { [[ -d "${dir}/.git" ]] || git_run "${dir}" rev-parse --git-dir > /dev/null 2>&1; } && \
                git_repos+=("${dir}")
        done
        shift
    done
}

main()
{
    get_repos "$@"

    [[ ! "${COLUMNS}" ]] && {
        shopt -s checkwinsize
        (:;:)
    }

    eval printf -v line "%0.s=" "{1..${COLUMNS:-$(tput cols)}}"

    for repo in "${git_repos[@]}"; do
        printf "Updating %s... " "${repo}"

        git_run "${repo}" fetch --quiet
        local_ref="$(git_run "${repo}" rev-parse HEAD)"
        remote_ref="$(git_run "${repo}" rev-parse @{u})"

        if [[ "${local_ref}" == "${remote_ref}" ]]; then
            printf "%s\\n" "Already up to date."
        else
            printf "\\n%s\\n" "${line}"
            git_run "${repo}" pull
            printf "%s\\n" "${line}"
        fi
    done
}

main "$@"
