#!/usr/bin/env bash

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              8

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config pointer_modifier        mod1
bspc config pointer_action1         move
bspc config pointer_action2         move
