#!/usr/bin/env bash

gaps="4"
focus_color="808080"
normal_color="404040"

! pgrep -x sxhkd > /dev/null 2>&1  && \
    sxhkd &

[[ -f "${HOME}/.fehbg" ]] && \
    bash "${HOME}/.fehbg"

type -p compton > /dev/null 2>&1 && \
    compton -b

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color    "#${focus_color}"
bspc config normal_border_color     "#${normal_color}"

bspc config border_width            2
bspc config window_gap              4

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false

bspc config pointer_modifier        mod1
bspc config pointer_action1         move
bspc config pointer_action2         move
