filetype plugin indent on

" Vim Settings
set tabpagemax=99
set nocompatible
set backspace=2
set hidden
set history=100
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set viminfo='50,<1000,s100,h
set conceallevel=0
set path+=**
autocmd BufRead scp://* :set bt=acwrite

" Aesthetics
set number
set laststatus=2
set noshowmode

" Force vim to use 16 colors
set t_Co=16

call matchadd('ColorColumn', '\%80v', 100)

if has('linebreak')
  set breakindent
  let &showbreak = '↳ '
  set cpo+=n
end

" Cursorline
set cursorline
set cursorcolumn

highlight CursorLine cterm=bold ctermbg=None
highlight CursorColumn cterm=bold ctermbg=None
highlight CursorLineNr cterm=bold ctermfg=None

" Highlight
highlight LineNr ctermfg=DarkGrey
highlight ColorColumn ctermbg=DarkGrey

" Search
set hlsearch
set showmatch
set incsearch

syntax on

" List of chars from Gozala
" https://github.com/Gozala/.vim/blob/master/.vimrc
set list
set listchars=tab:▸\ ,eol:¬,trail:˺,nbsp:█

" Redefine navigation with ctrl key in certain modes
nnoremap <C-h> <Left>
vnoremap <C-h> <Left>
inoremap <C-h> <Left>
cnoremap <C-h> <Left>

nnoremap <C-j> <Down>
inoremap <C-j> <Down>
vnoremap <C-j> <Down>

nnoremap <C-k> <Up>
inoremap <C-k> <Up>
vnoremap <C-k> <Up>

nnoremap <C-l> <Right>
inoremap <C-l> <Right>
vnoremap <C-l> <Right>
cnoremap <C-l> <Right>

" Disable arrows
nnoremap <Left> :echo "Nope."<CR>
vnoremap <Left> :<C-u>echo "Nope."<CR>
inoremap <Left> <C-o>:echo "Nope."<CR>
cnoremap <Left> <Nop>

nnoremap <Down> :echo "Nope."<CR>
vnoremap <Down> :<C-u>echo "Nope."<CR>
inoremap <Down> <C-o>:echo "Nope."<CR>

nnoremap <Up> :echo "Nope."<CR>
vnoremap <Up> :<C-u>echo "Nope."<CR>
inoremap <Up> <C-o>:echo "Nope."<CR>

nnoremap <Right> :echo "Nope."<CR>
vnoremap <Right> :<C-u>echo "Nope."<CR>
inoremap <Right> <C-o>:echo "Nope."<CR>
cnoremap <Right> <Nop>

" Set scoll
nnoremap <C-d> <PageUp>
vnoremap <C-d> <PageUp>
inoremap <C-d> <PageUp>

nnoremap <C-f> <PageDown>
vnoremap <C-f> <PageDown>
inoremap <C-f> <PageDown>

" Soft wrapping movements
nnoremap j gj
vnoremap j gj

nnoremap k gk
vnoremap k gk

" Block indent with visual mode
vnoremap > >gv
vnoremap < <gv

set pastetoggle=<F3>

" Disable json conceal
let g:vim_json_conceal=0

" Disable tex conceal
let g:tex_conceal=""

" Disable indentLine for these filetypes
autocmd FileType markdown let g:indentLine_enabled=0

" Lightline status line
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename' ] ],
      \ },
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }

function! LightlineFilename()
    let filename = expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
    let modified = &modified ? ' +' : ''
    return filename . modified
endfunction

" vim-lsc
let g:lsc_server_commands = {
      \ 'cs': 'omnisharp --languageserver'
      \ }

let g:lsc_auto_map = {
      \ 'defaults': v:true,
      \ }
