" Disabled plugins
let g:pathogen_disabled = ['vim-devicons']

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype plugin indent on

set nocompatible
set backspace=2
set number
set hidden
set history=100
set smartindent
set autoindent
set hlsearch
set showmatch
set tabstop=4
set shiftwidth=4
set expandtab
set laststatus=2
set noshowmode
"set cursorline
set path+=**
call matchadd('ColorColumn', '\%80v', 100)
autocmd BufRead scp://* :set bt=acwrite

highlight LineNr ctermfg=DarkGrey
highlight CursorLine cterm=NONE
highlight ColorColumn ctermbg=7

syntax on

" List of chars from Gozala
" https://github.com/Gozala/.vim/blob/master/.vimrc
set list
set listchars=tab:▸\ ,eol:¬,trail:˺,nbsp:█

" Remap semicolon to colon
nnoremap ; :

" Redefine navigation with ctrl key in certain modes
nnoremap <C-h> <Left>
vnoremap <C-h> <Left>
inoremap <C-h> <Left>
cnoremap <C-h> <Left>

nnoremap <C-j> <Down>
inoremap <C-j> <Down>
vnoremap <C-j> <Down>

nnoremap <C-k> <Up>
inoremap <C-k> <Up>
vnoremap <C-k> <Up>

nnoremap <C-l> <Right>
inoremap <C-l> <Right>
vnoremap <C-l> <Right>
cnoremap <C-l> <Right>

" Disable arrows
nnoremap <Left> :echo "Nope."<CR>
vnoremap <Left> :<C-u>echo "Nope."<CR>
inoremap <Left> <C-o>:echo "Nope."<CR>
cnoremap <Left> <Nop>

nnoremap <Down> :echo "Nope."<CR>
vnoremap <Down> :<C-u>echo "Nope."<CR>
inoremap <Down> <C-o>:echo "Nope."<CR>

nnoremap <Up> :echo "Nope."<CR>
vnoremap <Up> :<C-u>echo "Nope."<CR>
inoremap <Up> <C-o>:echo "Nope."<CR>

nnoremap <Right> :echo "Nope."<CR>
vnoremap <Right> :<C-u>echo "Nope."<CR>
inoremap <Right> <C-o>:echo "Nope."<CR>
cnoremap <Right> <Nop>

set pastetoggle=<F3>

" Lightline status line
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename' ] ],
      \ },
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }

function! LightlineFilename()
    let filename = expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
    let modified = &modified ? ' +' : ''
    return filename . modified
endfunction

" NerdTree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeWinSize = 36

" vim-markdown-preview
let vim_markdown_preview_github=1
