runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
filetype plugin indent on

set number
set hidden
set history=100
set smartindent
set autoindent
set hlsearch
set showmatch
set tabstop=4
set shiftwidth=4
set expandtab
set laststatus=2
set noshowmode
set cursorline

highlight LineNr ctermfg=DarkGrey
highlight CursorLine cterm=NONE

syntax on

" List of chars from Gozala
" https://github.com/Gozala/.vim/blob/master/.vimrc
set list
set listchars=tab:▸\ ,eol:¬,trail:˺,nbsp:█

" Lightline status line
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'readonly', 'filename' ] ],
      \ },
      \ 'component_function': {
      \   'filename': 'LightlineFilename',
      \ },
      \ }

function! LightlineFilename()
    let filename = expand('%:t') !=# '' ? expand('%:t') : '[No Name]'
    let modified = &modified ? ' +' : ''
    return filename . modified
endfunction

" NerdTree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeWinSize = 36
