#!/usr/bin/env bash

main()
{
    script="${HOME}/.dotfiles/scripts/info/show_cpu"
    mapfile -t cpu_info < <(bash "${script}" load temp fan)

    [[ "${cpu_info[*]}" ]] && {
        cpu_out="[ "
        for i in "${cpu_info[@]::${#cpu_info[@]} - 1}"; do
            cpu_out="${cpu_out}$i | "
        done
        cpu_out+="${cpu_info[@]:(-1):1} ]"
        printf "%s" "${cpu_out}"
    }
}

main
